pm_api_url          = "<proxmox url>"
pm_api_token_id     = "<proxmox token id>"
pm_api_token_secret = "<proxmox token secret>"
pm_node             = "<proxmox node name>"
pm_template         = "<proxmox tempalte>"